// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using URLShortener.Infrastructure.Context;

#nullable disable

namespace URLShortener.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("URLShortener.Domain.Entities.ClickEvent", builder =>
        {
            builder.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            builder.Property<string>("Browser")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            builder.Property<DateTime>("ClickedAt")
                .HasColumnType("datetime2");

            builder.Property<string>("CountryCode")
                .HasMaxLength(2)
                .HasColumnType("nvarchar(2)");

            builder.Property<string>("DeviceType")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            builder.Property<string>("ReferrerHost")
                .HasMaxLength(255)
                .HasColumnType("nvarchar(255)");

            builder.Property<Guid>("ShortenedUrlId")
                .HasColumnType("uniqueidentifier");

            builder.Property<string>("VisitorHash")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            builder.HasKey("Id");
            builder.HasIndex("VisitorHash");
            builder.HasIndex("ShortenedUrlId", "ClickedAt");
            builder.ToTable("ClickEvents");
        });

        modelBuilder.Entity("URLShortener.Domain.Entities.ShortenedUrl", builder =>
        {
            builder.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            builder.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");

            builder.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            builder.Property<DateTime?>("ExpiresAt")
                .HasColumnType("datetime2");

            builder.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(true);

            builder.Property<DateTime?>("LastAccessedAt")
                .HasColumnType("datetime2");

            builder.Property<string>("OriginalUrl")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            builder.Property<string>("ShortUrl")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            builder.Property<int>("TotalClicks")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasDefaultValue(0);

            builder.HasKey("Id");
            builder.HasIndex("Code").IsUnique();
            builder.ToTable("ShortenedUrls");
        });

        modelBuilder.Entity("URLShortener.Domain.Entities.ClickEvent", builder =>
        {
            builder.HasOne("URLShortener.Domain.Entities.ShortenedUrl", "ShortenedUrl")
                .WithMany("Clicks")
                .HasForeignKey("ShortenedUrlId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            builder.Navigation("ShortenedUrl");
        });

        modelBuilder.Entity("URLShortener.Domain.Entities.ShortenedUrl", builder =>
        {
            builder.Navigation("Clicks");
        });
#pragma warning restore 612, 618
    }
}
